HotKeySet("{NUMPAD0}", 'WindowSwitch')
HotKeySet("{NUMPAD1}", 'WindowSwitch')
HotKeySet("{NUMPAD2}", 'WindowSwitch')
HotKeySet("{NUMPAD3}", 'WindowSwitch')
HotKeySet("{NUMPAD4}", 'WindowSwitch')
HotKeySet("{NUMPAD5}", 'WindowSwitch')
HotKeySet("{NUMPAD6}", 'WindowSwitch')
HotKeySet("{NUMPAD7}", 'WindowSwitch')
HotKeySet("{NUMPAD8}", 'WindowSwitch')
HotKeySet("{NUMPAD9}", 'WindowSwitch')
HotKeySet("^{NUMPAD0}", 'WindowBind')
HotKeySet("^{NUMPAD1}", 'WindowBind')
HotKeySet("^{NUMPAD2}", 'WindowBind')
HotKeySet("^{NUMPAD3}", 'WindowBind')
HotKeySet("^{NUMPAD4}", 'WindowBind')
HotKeySet("^{NUMPAD5}", 'WindowBind')
HotKeySet("^{NUMPAD6}", 'WindowBind')
HotKeySet("^{NUMPAD7}", 'WindowBind')
HotKeySet("^{NUMPAD8}", 'WindowBind')
HotKeySet("^{NUMPAD9}", 'WindowBind')

Func WindowSwitch()
	$nickname = IniRead('config.ini', 'Hotkeys', @HotKeyPressed, '')
	WinActivate($nickname)
EndFunc

Func WindowBind()
	$hotkey = StringReplace(@HotKeyPressed, '^', '')
	IniWrite('config.ini', 'Hotkeys', $hotkey, ' ' & WinGetTitle(''))
EndFunc